### PR TITLE
No inline functions

### PR DESCRIPTION
**Pull request by danmcclain**

### CODE REVIEW

**Comment by brzpegasus** [comment]
Bleh. I like my inline functions for things like `filter`, `forEach`, etc.

**Comment by poteto** [comment]
Disagree, why eliminate lambdas?

**Comment by danmcclain** [comment]
Named functions provide more clarity into what you are doing, plus help with debugging of Promises

**Comment by poteto** [comment]
How do they help with debugging Promises? If you're using `filter` on a array of promises, then you should be using [`RSVP.filter`](http://emberjs.com/api/classes/RSVP.html#method_filter) anyway

**Comment by danmcclain** [comment]
When you chain promises, you get the name of the function in the promise panel in ember

**Comment by poteto** [comment]
Sure, but I don't think we should enforce throwing away one of the most useful features (lambdas) of the language

**Comment by poteto** [comment]
Perhaps we can update this to `prefer` over `must`

**Pull request closed without merging**
