### PR TITLE
Prefer destructuring Ember instead of using shims

### PR DESCRIPTION
**Pull request by duggiefresh**
* We'll continue to use modules for Ember Data though

### CODE REVIEW

**Comment by bcardarella** [comment]
:+1: also we should note that this is only until the shims have been made official.

**Comment by duggiefresh** [comment]
Sounds good, will update!

**Comment by rwjblue** [comment]
Well, they are official, you just don't like them :wink:

**Comment by duggiefresh** [comment]
Lol that is true, they are under the `ember-cli` org

**Comment by bcardarella** [comment]
@rwjblue this is where people get annoyed with core. We're told things are "official" then when they change we're told that it was "pre 1.0". I'd prefer not to opt our clients into something that could change in the future

**Comment by rwjblue** [comment]
> I'd prefer not to opt our clients into something that could change in the future

I totally understand!  I also agree with the silliness of some of the current module names in ember-cli-shims.

**Comment by rsocci** [comment]
LGTM :+1:

**Pull request merged**
