### PR TITLE
Change multi-line expression closing braces

### PR DESCRIPTION
**Pull request by courajs**
@dockyard/engineering any objections?

### CODE REVIEW

**Comment by danmcclain** [comment]
:+1: Let's see what others think though

**Comment by bcardarella** [comment]
I'm divided. Visually it seems odd to me, but I recognize that adding new params to the component is easier this way.

**Comment by danmcclain** [comment]
The other option is not to add new params at the bottom, but second from the bottom. I guess I am divided as well on this :trollface:

**Comment by poteto** [comment]
I like this, but I'm biased because I've been writing multiline HBS this way for a while

**Comment by rwjblue** [comment]
FWIW, I personally prefer to write multi line this way.

**Comment by brzpegasus** [comment]
It feels odd to me too, but could get used to it.

**Comment by drspaniel** [comment]
So seems like a few people think it feels weird, but no one disagrees that it would make us a little more efficient and a little less frustrated. I think we should merge

**Comment by danmcclain** [comment]
I'd like more of the team to chime in, it's only been open a few hours on a busy Friday

**Comment by bcardarella** [comment]
I think I'm going :-1: on this. I was considering how I might write multi-line HTML elements in place of a component:

```html
<x-thing
  foo="bar"
  bar="baz" />
```

vs


```html
<x-thing
  foo="bar"
  bar="baz"
/>
```

I think I would be more inclined to write the first style.

**Comment by danmcclain** [comment]
@bcardarella good point, I'm in agreement. If you need to add a new argument, you could put it the line above the closing tag. It's not that much harder to put the cursor before the closing tag anyway

(Closing tag meaning bracket or curly)

**Comment by bcardarella** [comment]
I'm not strongly opinionated about this to say we should have one over the other.

**Comment by drspaniel** [comment]
I started to become frustrated with the same-line closing bracket style, which is why I opened the pr. If the resolution is no merge, but I'm free to do it in code I'm working with, that's totally fine with me

**Comment by brzpegasus** [comment]
I definitely don't like this:

```html
<x-thing
  foo="bar"
  bar="baz"
/>
```

If having the dangling `}}` means we'll want to do the same for `>` or `/>` for consistency, then I'm not so much in favor of this rule.

**Comment by bcardarella** [comment]
@brzpegasus confirm, I definitely don't want to encourage this style when angle-bracket components come into play

**Comment by drspaniel** [comment]
What do the angle brackets change? It seems like the exact same set of pros and cons to me.
I also don't think we need to have the same set of rules for both. They can differ if we'd like

**Comment by bcardarella** [comment]
@drspaniel functionally, I don't think angle-brackets have any change. And this issue is clearly a very bike-shedy/opinionated/subjective discussion. I can't explain why, but the handlebars-style dangling closure doesn't bother me as much as the HTML one.

**Comment by bcardarella** [comment]
FWIW, I have gone back and forth on this with Elixir maps:

```elixir
%{
  foo: "bar",
  bar: "baz" }
```

vs

```elixir
%{
  foo: "bar",
  bar: "baz"
}
```

**Comment by bcardarella** [comment]
What is strange is that I do have a preference with arrays:

```elixir
[
  "foo",
  "bar",
  "baz" ]
```

vs

```
[
  "foo",
  "bar",
  "baz"
]
```

With arrays I prefer the first style.

All of these use-cases are essentially identical. I can't articulate why it seems different to me in different cases.

**Comment by poteto** [comment]
Yes this is very subjective, and perhaps should not be mandated in the style guide. Personally I'm okay with the closing tag being on a newline, the same way I prefer closing braces and brackets in js

**Comment by poteto** [comment]
I think the main point is that the new line closing tag ensures that it is not annoying to add a new attribute/key/value/whatever. The same line closing tag makes that annoying and also will likely cause funky merge issues if you try to avoid adding attributes to the end of the thing. 

So while aesthetically it might not be the most pleasing, I favor developer ergonomics so I'm :+1: on this

**Comment by brzpegasus** [comment]
What if it's used as a block component?

Are we still okay with this:

```hbs
{{#x-thing
    value=blah
    options=options
    label="thing"
}}
  <div>some content</div>
{{/x-thing}}
```

rather than this:

```hbs
{{#x-thing
    value=blah
    options=options
    label="thing"}}
  <div>some content</div>
{{/x-thing}}
```

**Comment by poteto** [comment]
Although it looks odd in the first example, it still reads better. You can very easily see where the opening tag ends. The 2nd example makes it difficult to scan, you have to spend more time trying to locate the end of the closing tag, and visually it almost looks as if the `div` tag is _inside_ the opening tag

**Comment by drspaniel** [comment]
So I think we'll close this, leaving it up to personal taste?

**Comment by brzpegasus** [comment]
No, I think we should come to a consensus. I'd rather not see two different styles in the same template and/or project. Maybe finalize at the next engineering meeting?

**Comment by danmcclain** [comment]
Bare knuckle brawl to decide, pick teams wisely :facepunch:

**Comment by duggiefresh** [comment]
I believe we concluded to close this issue for now.

**Pull request closed without merging**
