### PR TITLE
Fixes #122 - Update Declaration Order with better descriptive comments

### LINKED ISSUE #122: Update the OOD list to include height and width

### PR DESCRIPTION
**Pull request by Ctannerweb**
Update Declaration Order with descriptive comments that better outline why CSS properties are in the order they are in.

### CODE REVIEW

**Comment by jdsteinbach** [comment]
👍

**Comment by davidluhr** [comment]
Looks good! Yesterday, @ChrisGoodwin mentioned that `height` should be arranged before `width`. Is this a team-wide convention? Similar question for `z-index` appearing before `top, right, bottom, left`.

**Comment by Ctannerweb** [comment]
Honestly, as you can tell from my commit I put width first lol... In my head I go with width first because `100x50` = `width: 100` `height: 50;` when you read it out.

**Comment by ChrisGoodwin** [comment]
Alphabetical though...

**Comment by Ctannerweb** [comment]
But would this count as a shorthand exception???

**Comment by danrichman** [comment]
I think width before height is pretty standard in most tools.

untitled

**Comment by jdsteinbach** [comment]
CSS shorthand is `width` then `height` - for example, background-position & translate/scale shorthand.

**Comment by Ctannerweb** [comment]
oops

**Pull request merged**
