### PR TITLE
Github open source project template

### PR DESCRIPTION
**Pull request by martndemus**
- [x] README.md
- [x] CONTRIBUTING.md
- [x] ISSUE_TEMPLATE.md
- [x] PULL_REQUEST_TEMPLATE.md
- [x] CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martndemus** [comment]
Added ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

**Comment by bcardarella** [comment]
:+1:

**Comment by bcardarella** [comment]
Is there anything holding this up from merging?

**Comment by martndemus** [comment]
People reviewing it

**Comment by bcardarella** [comment]
It seems OK to me

**Comment by rsocci** [comment]
LGTM

**Comment by bcardarella** [comment]
@rsocci can you coordinate getting these into our projects?

**Comment by rsocci** [comment]
@bcardarella 👍

**Pull request merged**
